name: OSINT Parser CI

on: [push, pull_request]

jobs:
  security-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Security Check (Bandit)
        run: |
          bandit main.py

      - name: Run Tests (Pytest)
        run: |
          python -m pytest